name: Download and Export Keycloak Image
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: keycloak
  IMAGE_TAG: 18.0.2
  IMAGE_SOURCE: keycloak
  REGISTRY: quay.io

jobs:
  export-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull target image
        run: docker pull quay.io/$IMAGE_SOURCE/$IMAGE_NAME:$IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ secrets.QUAYIO_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.QUAYIO_PWD }}

      - name: Tag downloaded image
        run: docker tag quay.io/$IMAGE_SOURCE/$IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$IMAGE_TAG

      - name: Save tagged image
        run: docker save -o $IMAGE_NAME-$IMAGE_TAG.tar $IMAGE_NAME:$IMAGE_TAG

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: $IMAGE_NAME-$IMAGE_TAG
          path: $IMAGE_NAME-$IMAGE_TAG.tar

