name: Download RPM Packages
  on:
    workflow_dispatch:
      inputs:
        images:
          description: 'Nom de l'image à télécharger'
          required: true
          default: 'nginx'
        registry:
          description: "Registre à partir duquel télécharger l'image"
          required: false
          default: 'docker.io'
        image_path:
          description: "Chemin au sein du repo de l'image"
          required: true
          default: "/"
        image_tag:
          description: "Version de l'image à télécharger
          required: true
          default: latest
        container_engine:
          description: 'Podman ou Docker, conditionne quel CLI est utilisé'
          required: true
          type: choice
          options:
            - docker
            - podman
          default: docker
        artifact_name:
          description: "Nom de l'artefact exporté"
          required: true
          default: 'image'

jobs:
  pull_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull target image
        run: ${{ inputs.container_engine }} pull ${{ inputs.registry }}${{inputs.image_path}}${{ inputs.image }}:${{ inputs.image_tag }}
        env:
          DOCKER_USERNAME: ${{ secrets.QUAYIO_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.QUAYIO_PWD }}

      - name: Tag downloaded image
        run: |
              docker tag ${{ inputs.registry }}${{inputs.image_path}}${{ inputs.image }}:${{ inputs.image_tag }} \
                         ${{ inputs.image }}:${{ inputs.image_tag }}

      - name: Save tagged image
        run: |
              ${{ inputs.container_engine }} save -o ${{ inputs.image }}-${{ inputs.image_tag }}.tar \
              ${{ inputs.image }}:${{ inputs.image_tag }}
  
  upload_image:
      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image }}-${{ inputs.image_tag }}
          path: ${{ inputs.image }}-${{ inputs.image_tag }}.tar

