name: Download Docker RPMs

on:
  workflow_dispatch:

jobs:
  download-rpms:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          mkdir -p docker-rpms

      - name: Download Docker RPMs
        run: |
          curl -fsSL https://download.docker.com/linux/centos/docker-ce.repo -o docker-ce.repo
          sudo mv docker-ce.repo /etc/yum.repos.d/
          
          sudo apt-get update
          sudo apt-get install -y yum-utils
          
          cd docker-rpms
          yumdownloader --resolve docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-swarm
          

      - name: Archive RPMs
        run: |
          tar -czvf docker-rpms.tar.gz docker-rpms/

      - name: Upload RPM archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-rpms-archive
          path: docker-rpms.tar.gz
          retention-days: 7
